countries = [
    {"name": "India", "capital": "New Delhi", "continent": "Asia", "population": 1428627663},
    {"name": "China", "capital": "Beijing", "continent": "Asia", "population": 1412600000},
    {"name": "United States", "capital": "Washington D.C.", "continent": "North America", "population": 339996563},
    {"name": "Indonesia", "capital": "Jakarta", "continent": "Asia", "population": 277534122},
    {"name": "Pakistan", "capital": "Islamabad", "continent": "Asia", "population": 241499431},
    {"name": "Brazil", "capital": "Brasília", "continent": "South America", "population": 216422446},
    {"name": "Nigeria", "capital": "Abuja", "continent": "Africa", "population": 227882945},
    {"name": "Bangladesh", "capital": "Dhaka", "continent": "Asia", "population": 172954319},
    {"name": "Russia", "capital": "Moscow", "continent": "Europe", "population": 146447424},
    {"name": "Mexico", "capital": "Mexico City", "continent": "North America", "population": 129875529},

    {"name": "Japan", "capital": "Tokyo", "continent": "Asia", "population": 123294513},
    {"name": "Ethiopia", "capital": "Addis Ababa", "continent": "Africa", "population": 126527060},
    {"name": "Philippines", "capital": "Manila", "continent": "Asia", "population": 117337368},
    {"name": "Egypt", "capital": "Cairo", "continent": "Africa", "population": 112716598},
    {"name": "Vietnam", "capital": "Hanoi", "continent": "Asia", "population": 98858950},
    {"name": "Germany", "capital": "Berlin", "continent": "Europe", "population": 83294633},
    {"name": "Turkey", "capital": "Ankara", "continent": "Asia", "population": 85816199},
    {"name": "United Kingdom", "capital": "London", "continent": "Europe", "population": 67736802},
    {"name": "France", "capital": "Paris", "continent": "Europe", "population": 64756584},
    {"name": "Italy", "capital": "Rome", "continent": "Europe", "population": 58870762},

    {"name": "South Africa", "capital": "Pretoria", "continent": "Africa", "population": 60414495},
    {"name": "Tanzania", "capital": "Dodoma", "continent": "Africa", "population": 67438106},
    {"name": "Myanmar", "capital": "Naypyidaw", "continent": "Asia", "population": 54577997},
    {"name": "South Korea", "capital": "Seoul", "continent": "Asia", "population": 51784059},
    {"name": "Colombia", "capital": "Bogotá", "continent": "South America", "population": 52085168},
    {"name": "Spain", "capital": "Madrid", "continent": "Europe", "population": 48373341},
    {"name": "Argentina", "capital": "Buenos Aires", "continent": "South America", "population": 45538401},
    {"name": "Algeria", "capital": "Algiers", "continent": "Africa", "population": 45606480},
    {"name": "Sudan", "capital": "Khartoum", "continent": "Africa", "population": 48109006},
    {"name": "Canada", "capital": "Ottawa", "continent": "North America", "population": 40097761}
]
